### ISSUE TITLE
check: SSL connect error

### ISSUE THREAD

**Issue by yukiryo** [YuehaiTeam/zhiqiong#1]
![image](https://user-images.githubusercontent.com/58250223/171983864-9a284f5d-0149-4f26-b995-8c09bc872792.png)

**Comment by xytoki** [comment]
网络相关问题导致无法连接更新检查服务器，不是特别好排查，可能和系统设置里的SSL设置有关，可以在cmd里尝试curl https://cocogoat-1251105598.file.myqcloud.com/77/

**Comment by xytoki** [comment]
已修复，暂未发版。
（ https://github.com/YuehaiTeam/frostflake/commit/78388a635bcf01758c40dabbc7488cdf8e2cb7af ）

**Comment by xytoki** [comment]
已在1.2.5发版（一个月前，忘记close了）。
