### ISSUE TITLE
用户有什么方法可以手动应用 cvautotrack.dll？

### ISSUE THREAD

**Issue by CODE-LA-LI-LU-LE-LO** [YuehaiTeam/zhiqiong#11]
我想使用最新版本的 cvautotrack.dll。
用户有什么方法可以手动应用 cvautotrack.dll？

-----
I want to use the latest version of cvautotrack.dll.
Is there any way for the user to manually apply cvautotrack.dll?

**Comment by xytoki** [comment]
First create a folder `cocogoat-noupdate` in the same dir with `cocogoat-control.exe`  to disable auto update, then replace the dll file.

----
在`cocogoat-control.exe`的同目录下创建`cocogoat-noupdate`文件夹以禁用自动更新，然后手动替换dll文件即可。

**Comment by CODE-LA-LI-LU-LE-LO** [comment]
我解压了版本 [6.5.92](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/releases/tag/6.5.92)的 cvAutoTrack.7z，但我失败了：loadlibrary 1114 '跟踪地图加载失败！ '
还有什么我需要做的吗？

---
I unpacked cvAutoTrack.7z of release ver [6.5.92](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/releases/tag/6.5.92), but I get failed: loadlibrary 1114 'Failed to load cvautotrack!'.
Is there anything else I need to do?

**Comment by xytoki** [comment]
Maybe this dll has an incompatible ABI. I'll check it in a few days.

---

这个版本的dll似乎有API/ABI上的更改。我这几天检查一下。

**Comment by CODE-LA-LI-LU-LE-LO** [comment]
22.10.18
cvAutoTrack 6.5.92 版仍然不起作用。
使用[7.1.6](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/releases/tag/7.1.6)版本时，出现如下错误。
```
跟踪地图加载失败!
faild:getprocaddr 127
```

=====
22.10.18
cvAutoTrack Version 6.5.92 still doesn't work.
When using the [7.1.6](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/releases/tag/7.1.6) version, the following error occurs.

**Comment by xytoki** [comment]
cvAutoTrack v7有 **巨大的** API改动，所以和当前版本的`cocogoat-control`完全不兼容。我正在适配，但它还不稳定，甚至在我的电脑上完全无法工作。

------

cvAutoTrack v7 has BIG API CHANGES so it can't be used with current version of cocogoat-control. I'm developing new versions to adapt it but it is still unstable.

**Comment by xytoki** [comment]
我已经适配了`cvautotrack  v7.2.3`。你需要升级`cocogoat-control`到`v1.3.0`，之后dll会被自动更新。新版本同时增加了地下地图的功能，并为二维码分享添加了实验性的HoyoLab支持。

----
I've adapted `cvautotrack  v7.2.3`. To use this version, you should upgrade `cocogoat-control` to `v1.3.0`, then follow the auto upgrade of the dll. This new version also added support of qr code sharing for the Hoyolab Map, and a feature to show underground maps.

**Comment by CODE-LA-LI-LU-LE-LO** [comment]
这工作正常。
但是当我单击禁用/启用当前位置跟踪和二维码的按钮时，它不起作用并转到 'about:blank'。

===

This works fine.
But when I click the button which disables/enables current location tracking and QR Code, it doesn't work and goes to 'about:blank'.

**Comment by xytoki** [comment]
应该修好了。在浏览器里，由于油猴脚本存在每日只能自动更新一次的限制，用户可能需要重新安装一下油猴脚本，在UWP APP里则需要等待5-10分钟使缓存过期。

----
It may be fixed in the last commit. For the browser, users may need to reinstall the userscript because userscripts can only trigger auto update once a day. For the uwp app, you may need to wait about 5-10 minutes so cached data will expire.

**Comment by CODE-LA-LI-LU-LE-LO** [comment]
该按钮工作正常。
位置跟踪有问题，但似乎是 cvautotrack.dll 有问题。

---

The button works fine.
There is a problem with the location tracking, but it seems to be a problem with cvautotrack.dll.

**Comment by xytoki** [comment]
右键点击定位跟随开关图标可以获得cvautotrack生成的调试图片，这可能会对检查问题有用。

----
You can right click the location icon to get debug image from cvautotrack, which may be useful for debugging.

**Comment by CODE-LA-LI-LU-LE-LO** [comment]
谢谢你! 我会试试看

---
Thank you! I'll try it.
