### ISSUE TITLE
地图识别失败：Bitblt模式下未能检测到派蒙

### ISSUE THREAD

**Issue by Bilx-ZL** [YuehaiTeam/zhiqiong#12]
地图识别失败：Bitblt模式下未能检测到派蒙

在Win11设置【_系统-屏幕-显示卡-更改默认图形设置_】中关闭**窗口化游戏优化**

**Comment by yxok200** [comment]
+1
一直报错，搜索派蒙图标位置失败

**Comment by D4box** [comment]
派蒙图标位置失败显示切换到DX11模式，霜华退出后不再重启

**Comment by HuanLinOTO** [comment]
+1 我也是

**Comment by Bilx-ZL** [comment]
每次看到抄送，还以为解决了，结果是群发性故障

**Comment by HuanLinOTO** [comment]
> 每次看到抄送，还以为解决了，结果是群发性故障

看到你的我也以为解决了。。

**Comment by xytoki** [comment]
报错有没有变化？前段时间推送了一个新版，应该会输出更精确的错误码和信息，现在还是提示“搜索派蒙图标位置失败”吗？

**Comment by xytoki** [comment]
这问题现在只能尝试给cvautotrack的算法做优化，一周多之前推的那个版本主要是修了疯狂尝试切换DX模式问题和优化FSR下的成功率，但对于有的设备SMAA下都识别不出来的情况还没处理。如果还有这两问题可以试试找一下`autotrack.log`传到这里（通常在`C:\Program Files\cocogoat-control`目录下，如果不在就在`C:\Windows\System32`）

**Comment by HuanLinOTO** [comment]
> 这问题现在只能尝试给cvautotrack的算法做优化，一周多之前推的那个版本主要是修了疯狂尝试切换DX模式问题和优化FSR下的成功率，但对于有的设备SMAA下都识别不出来的情况还没处理。如果还有这两问题可以试试找一下`autotrack.log`传到这里（通常在`C:\Program Files\cocogoat-control`目录下，如果不在就在`C:\Windows\System32`）

忘了提issue的基本要素
## 系统环境
Windows11 21h2 22000.1335
## 语言环境（丢全局了的）
Python3.7.9 Node.js16.15.1(npm8.18.0) jdk17 gcc4.9.2
## 椰羊各应用版本
霜华v1.3.0
志琼(不知道,昨天从官网覆盖安装了最新版本)
## 截图
![image](https://user-images.githubusercontent.com/94176676/209886950-3694b03f-3b8e-4438-8e1b-15a486868f9b.png)
## 原神分辨率
1980*700
## Log
https://pastebin.com/PXM4tyBq

**Comment by sylar605** [comment]
2022-12-29 15:31:31 | 错误代码：3001  ，错误信息：获取视角朝向时，没有识别到paimon
2022-12-29 15:31:32 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:32 | 错误代码：1001  ，错误信息：GetTransformOfMap: 标定小地图区域失败
2022-12-29 15:31:32 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:32 | 错误代码：3001  ，错误信息：获取视角朝向时，没有识别到paimon
2022-12-29 15:31:33 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:33 | 错误代码：1001  ，错误信息：GetTransformOfMap: 标定小地图区域失败
2022-12-29 15:31:33 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:33 | 错误代码：3001  ，错误信息：获取视角朝向时，没有识别到paimon
2022-12-29 15:31:34 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:34 | 错误代码：1001  ，错误信息：GetTransformOfMap: 标定小地图区域失败
2022-12-29 15:31:34 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:34 | 错误代码：3001  ，错误信息：获取视角朝向时，没有识别到paimon
2022-12-29 15:31:34 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:34 | 错误代码：1001  ，错误信息：GetTransformOfMap: 标定小地图区域失败
2022-12-29 15:31:34 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:34 | 错误代码：3001  ，错误信息：获取视角朝向时，没有识别到paimon
2022-12-29 15:31:35 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:35 | 错误代码：1001  ，错误信息：GetTransformOfMap: 标定小地图区域失败
2022-12-29 15:31:35 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:35 | 错误代码：3001  ，错误信息：获取视角朝向时，没有识别到paimon
2022-12-29 15:31:36 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:36 | 错误代码：1001  ，错误信息：GetTransformOfMap: 标定小地图区域失败
2022-12-29 15:31:36 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 15:31:36 | 错误代码：3001  ，错误信息：获取视角朝向时，没有识别到paimon

**Comment by Bilx-ZL** [comment]
> 

因为常年故障状态，后面没用了。我刚才去看了下，和 @sylar605一样的情况，报错和日志一模一样。

![屏幕截图_20221229_185644](https://user-images.githubusercontent.com/104142438/209942583-5b4639aa-6567-4833-9549-d2819f82c852.jpg)
<img width="700" alt="屏幕截图 2022-12-29 190553" src="https://user-images.githubusercontent.com/104142438/209942589-100dcfd9-bf02-4626-b867-fe7390a84854.png">

**Comment by HuanLinOTO** [comment]
---我原本想逝逝能不能编译一份霜华来尝试提供更多信息的 却发现好像缺个MfcClass（翻烂了github和baidu+bing都没找到带Manager.h的）个人没干过c系列语言开发---
草 我傻逼了 没看到lib文件夹里有

**Comment by xytoki** [comment]
> ---我原本想逝逝能不能编译一份霜华来尝试提供更多信息的 却发现好像缺个MfcClass（翻烂了github和baidu+bing都没找到带Manager.h的）个人没干过c系列语言开发--- 草 我傻逼了 没看到lib文件夹里有

问题不会在霜华里，在cvautotrack.dll的识别算法，cvautotrack.dll是每次开始识别的时候热更新的。比如说50001的错误码在这里：

https://github.com/YuehaiTeam/GenshinImpact_AutoTrack_DLL/blob/8fe4cf5ea9745314692d06becfe65c96829c9383/cvAutoTrack/src/AutoTrack.cpp#L857-L861

然后造成50001的参数在这里：
https://github.com/YuehaiTeam/GenshinImpact_AutoTrack_DLL/blob/8fe4cf5ea9745314692d06becfe65c96829c9383/cvAutoTrack/src/match/match_minimap.cpp#L85

**Comment by sylar605** [comment]
大概率原因是Bitblt模式不支持win11

**Comment by HuanLinOTO** [comment]
\

> 大概率原因是Bitblt模式不支持win11

我在7月份左右用的时候没问题的啊 难不成7月份之后换了？

**Comment by xytoki** [comment]
> \
> 
> > 大概率原因是Bitblt模式不支持win11
> 
> 我在7月份左右用的时候没问题的啊 难不成7月份之后换了？

十月底依赖的cvautotrack更新到了v7，有大量的实现方式和接口改变；
然后确实是有Bitblt模式不支持win11的说法，但是目前只在Win11 Dev Preview下有出现（我未验证，参照 GengGode/GenshinImpact_AutoTrack_DLL/issues/30 ），而且cvautotrack的dx实现有比较大的精度问题

**Comment by sylar605** [comment]
> > \
> > > 大概率原因是Bitblt模式不支持win11
> > 
> > 
> > 我在7月份左右用的时候没问题的啊 难不成7月份之后换了？
> 
> 十月底依赖的cvautotrack更新到了v7，有大量的实现方式和接口改变； 然后确实是有Bitblt模式不支持win11的说法，但是目前只在Win11 Dev Preview下有出现（我未验证，参照 [GengGode/GenshinImpact_AutoTrack_DLL/issues/30](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/issues/30) ），而且cvautotrack的dx实现有比较大的精度问题

似乎是更新了22H2？我这边似乎是22H2后出现不行的

**Comment by HuanLinOTO** [comment]
> > \
> > > 大概率原因是Bitblt模式不支持win11
> > 
> > 
> > 我在7月份左右用的时候没问题的啊 难不成7月份之后换了？
> 
> 十月底依赖的cvautotrack更新到了v7，有大量的实现方式和接口改变； 然后确实是有Bitblt模式不支持win11的说法，但是目前只在Win11 Dev Preview下有出现（我未验证，参照 [GengGode/GenshinImpact_AutoTrack_DLL/issues/30](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/issues/30) ），而且cvautotrack的dx实现有比较大的精度问题

要不我试试管理员运行霜华插件 and dll编译这块的话我有一台V100炼丹机 应该可以搭建workflow cpu一直吃满，gpu轻松摸鱼这种局面太难受了（）

**Comment by HuanLinOTO** [comment]
> > > \
> > > > 大概率原因是Bitblt模式不支持win11
> > > 
> > > 
> > > 我在7月份左右用的时候没问题的啊 难不成7月份之后换了？
> > 
> > 
> > 十月底依赖的cvautotrack更新到了v7，有大量的实现方式和接口改变； 然后确实是有Bitblt模式不支持win11的说法，但是目前只在Win11 Dev Preview下有出现（我未验证，参照 [GengGode/GenshinImpact_AutoTrack_DLL/issues/30](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/issues/30) ），而且cvautotrack的dx实现有比较大的精度问题
> 
> 似乎是更新了22H2？我这边似乎是22H2后出现不行的

我21h2 也有
![image](https://user-images.githubusercontent.com/94176676/209947548-85a775bb-e571-4ad2-b257-a2fe19c9f1f4.png)

**Comment by xytoki** [comment]
我目前是22H2 Release Preview，自己机子是能正常的；dll编译有action，可以fork了然后用action跑一下。
只调试DLL、不开霜华和志琼的方法：
下载[`TEST_cvAutoTrack_Cpp.exe`](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/releases/download/7.3.3/TEST_cvAutoTrack_Cpp.exe) ([来源：GengGode/GenshinImpact_AutoTrack_DLL/releases/tag/7.3.3](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/releases/tag/7.3.3))，和DLL放一起，管理员身份运行，就能直接调dll的接口，方便确认问题

**Comment by sylar605** [comment]
> > > \
> > > > 大概率原因是Bitblt模式不支持win11
> > > 
> > > 
> > > 我在7月份左右用的时候没问题的啊 难不成7月份之后换了？
> > 
> > 
> > 十月底依赖的cvautotrack更新到了v7，有大量的实现方式和接口改变； 然后确实是有Bitblt模式不支持win11的说法，但是目前只在Win11 Dev Preview下有出现（我未验证，参照 [GengGode/GenshinImpact_AutoTrack_DLL/issues/30](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/issues/30) ），而且cvautotrack的dx实现有比较大的精度问题
> 
> 要不我试试管理员运行霜华插件 and dll编译这块的话我有一台V100炼丹机 应该可以搭建workflow cpu一直吃满，gpu轻松摸鱼这种局面太难受了（）

我试过用浏览器油猴版+管理员启动浏览器+管理员启动椰羊插件 不行 报一样的错

**Comment by xytoki** [comment]
目前看来两个可能性比较大，一个是bitblt抓到的图有问题，一个是cvautotrack的识别算法有问题。
上面的调试exe可以直接生成截图，可以看看bitblt能不能抓到，以及会不会有之前有人说的只能抓一帧后面就没了或者重复了的问题

**Comment by sylar605** [comment]
试了下OBS的bitblt一切正常

**Comment by sylar605** [comment]
一开始提示
2022-12-29 20:06:06 | 错误代码：40001 ，错误信息：Bitblt模式下检测派蒙失败
2022-12-29 20:06:06 | 错误代码：1001  ，错误信息：GetTransformOfMap: 标定小地图区域失败
2022-12-29 20:06:20 | 错误代码：251   ，错误信息：画面为空
2022-12-29 20:06:22 | 错误代码：251   ，错误信息：画面为空
2022-12-29 20:06:22 | 错误代码：251   ，错误信息：画面为空
2022-12-29 20:06:24 | 错误代码：251   ，错误信息：画面为空
2022-12-29 20:06:25 | 错误代码：251   ，错误信息：画面为空
2022-12-29 20:06:43 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙
2022-12-29 20:06:43 | 错误代码：1001  ，错误信息：获取坐标时，没有识别到paimon

然后07分 08分截图成功
再截图就是同一帧 永远停留在同一帧

**Comment by HuanLinOTO** [comment]
> 一开始提示 2022-12-29 20:06:06 | 错误代码：40001 ，错误信息：Bitblt模式下检测派蒙失败 2022-12-29 20:06:06 | 错误代码：1001 ，错误信息：GetTransformOfMap: 标定小地图区域失败 2022-12-29 20:06:20 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:22 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:22 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:24 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:25 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:43 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙 2022-12-29 20:06:43 | 错误代码：1001 ，错误信息：获取坐标时，没有识别到paimon
> 
> 然后07分 08分截图成功 再截图就是同一帧 永远停留在同一帧

ummm调试工具的截图保存到哪里了

**Comment by HuanLinOTO** [comment]
连续执行了两次2
2022-12-29 20:12:19 | 错误代码：251   ，错误信息：画面为空
2022-12-29 20:13:29 | 错误代码：251   ，错误信息：画面为空

**Comment by HuanLinOTO** [comment]
![image](https://user-images.githubusercontent.com/94176676/209949856-bf485733-907d-4602-9db3-089a974de88b.png)
我obs也没问题

**Comment by HuanLinOTO** [comment]
dx截图可用吗？也不行

**Comment by sylar605** [comment]
> > 一开始提示 2022-12-29 20:06:06 | 错误代码：40001 ，错误信息：Bitblt模式下检测派蒙失败 2022-12-29 20:06:06 | 错误代码：1001 ，错误信息：GetTransformOfMap: 标定小地图区域失败 2022-12-29 20:06:20 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:22 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:22 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:24 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:25 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:43 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙 2022-12-29 20:06:43 | 错误代码：1001 ，错误信息：获取坐标时，没有识别到paimon
> > 然后07分 08分截图成功 再截图就是同一帧 永远停留在同一帧
> 
> ummm调试工具的截图保存到哪里了

同目录

**Comment by HuanLinOTO** [comment]
> > > 一开始提示 2022-12-29 20:06:06 | 错误代码：40001 ，错误信息：Bitblt模式下检测派蒙失败 2022-12-29 20:06:06 | 错误代码：1001 ，错误信息：GetTransformOfMap: 标定小地图区域失败 2022-12-29 20:06:20 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:22 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:22 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:24 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:25 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:43 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙 2022-12-29 20:06:43 | 错误代码：1001 ，错误信息：获取坐标时，没有识别到paimon
> > > 然后07分 08分截图成功 再截图就是同一帧 永远停留在同一帧
> > 
> > 
> > ummm调试工具的截图保存到哪里了
> 
> 同目录

251 截图失败
那是不是就没有输出

**Comment by sylar605** [comment]
> > > > 一开始提示 2022-12-29 20:06:06 | 错误代码：40001 ，错误信息：Bitblt模式下检测派蒙失败 2022-12-29 20:06:06 | 错误代码：1001 ，错误信息：GetTransformOfMap: 标定小地图区域失败 2022-12-29 20:06:20 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:22 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:22 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:24 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:25 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:43 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙 2022-12-29 20:06:43 | 错误代码：1001 ，错误信息：获取坐标时，没有识别到paimon
> > > > 然后07分 08分截图成功 再截图就是同一帧 永远停留在同一帧
> > > 
> > > 
> > > ummm调试工具的截图保存到哪里了
> > 
> > 
> > 同目录
> 
> 251 截图失败 那是不是就没有输出

对 我报251也没有输出 然后多截几张又成功了

**Comment by HuanLinOTO** [comment]
> > > > > 一开始提示 2022-12-29 20:06:06 | 错误代码：40001 ，错误信息：Bitblt模式下检测派蒙失败 2022-12-29 20:06:06 | 错误代码：1001 ，错误信息：GetTransformOfMap: 标定小地图区域失败 2022-12-29 20:06:20 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:22 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:22 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:24 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:25 | 错误代码：251 ，错误信息：画面为空 2022-12-29 20:06:43 | 错误代码：50001 ，错误信息：Bitblt模式下未能检测到派蒙 2022-12-29 20:06:43 | 错误代码：1001 ，错误信息：获取坐标时，没有识别到paimon
> > > > > 然后07分 08分截图成功 再截图就是同一帧 永远停留在同一帧
> > > > 
> > > > 
> > > > ummm调试工具的截图保存到哪里了
> > > 
> > > 
> > > 同目录
> > 
> > 
> > 251 截图失败 那是不是就没有输出
> 
> 对 我报251也没有输出 然后多截几张又成功了

我2 9交替执行 一直没成功

**Comment by xytoki** [comment]
草，我自己试了一下，得先按3再按9才能截到图，吐血

**Comment by HuanLinOTO** [comment]
草 截图成功了
![Capture](https://user-images.githubusercontent.com/94176676/209950483-73ab28be-a567-4e1d-8980-8e4c0088b507.png)
但是全透明

**Comment by HuanLinOTO** [comment]
> 草，我自己试了一下，得先按3再按9才能截到图，吐血

3不是获取坐标角度么

**Comment by xytoki** [comment]
我大概找到22H2影响截图的设置了，关掉“窗口化游戏优化”试试？我自己机子一开这个就抓不到图，关掉就可以，你们试试

![Snipaste_2022-12-29_20-23-07](https://user-images.githubusercontent.com/7547189/209950665-d3b9ae8e-035c-4de9-9cc4-8c5fed0c0542.png)

微软文档（机翻）：
https://support.microsoft.com/zh-cn/windows/windows-11%E4%B8%AD%E7%AA%97%E5%8F%A3%E5%8C%96%E6%B8%B8%E6%88%8F%E7%9A%84%E4%BC%98%E5%8C%96-3f006843-2c7e-4ed0-9a5e-f9389e535952

**Comment by HuanLinOTO** [comment]
> 我大概找到22H2影响截图的设置了，关掉“窗口化游戏优化”试试？我自己机子一开这个就抓不到图，关掉就可以，你们试试
> 
> ![Snipaste_2022-12-29_20-23-07](https://user-images.githubusercontent.com/7547189/209950665-d3b9ae8e-035c-4de9-9cc4-8c5fed0c0542.png)
> 
> 微软文档（机翻）： https://support.microsoft.com/zh-cn/windows/windows-11%E4%B8%AD%E7%AA%97%E5%8F%A3%E5%8C%96%E6%B8%B8%E6%88%8F%E7%9A%84%E4%BC%98%E5%8C%96-3f006843-2c7e-4ed0-9a5e-f9389e535952

![image](https://user-images.githubusercontent.com/94176676/209950820-89c339dd-e750-4e40-8758-d060a5161f16.png)
我咋没（）

**Comment by xytoki** [comment]
> > 草，我自己试了一下，得先按3再按9才能截到图，吐血
> 
> 3不是获取坐标角度么

这调试器调用函数的时候不会执行init，只按9连句柄都没拿到...
按3是强制跑一下init

**Comment by HuanLinOTO** [comment]
> > > 草，我自己试了一下，得先按3再按9才能截到图，吐血
> > 
> > 
> > 3不是获取坐标角度么
> 
> 这调试器调用函数的时候不会执行init，只按9连句柄都没拿到... 按3是强制跑一下init

草 有无可能是nvidia experience的问题（

**Comment by HuanLinOTO** [comment]
我截图成功了
![image](https://user-images.githubusercontent.com/94176676/209951238-d9deb7c7-ec25-467d-8a81-14862c018f57.png)
但是这为什么中间有陀透明的

**Comment by xytoki** [comment]
> 我截图成功了 ![image](https://user-images.githubusercontent.com/94176676/209951238-d9deb7c7-ec25-467d-8a81-14862c018f57.png) 但是这为什么中间有陀透明的

估计是哪里把RGB通道写到A通道去了，这个理论上不影响才对？其他部分的颜色都是正常的

**Comment by HuanLinOTO** [comment]
> > 我截图成功了 ![image](https://user-images.githubusercontent.com/94176676/209951238-d9deb7c7-ec25-467d-8a81-14862c018f57.png) 但是这为什么中间有陀透明的
> 
> 估计是哪里把RGB通道写到A通道去了，这个理论上不影响才对？其他部分的颜色都是正常的

ummm不知道 我调试工具运行了3之后退出了。。。

**Comment by xytoki** [comment]
如果确实是截不到图，但是obs的bitblt又可以，可能就得去找一下bitblt的参数一致性问题了

**Comment by HuanLinOTO** [comment]
> 如果确实是截不到图，但是obs的bitblt又可以，可能就得去找一下bitblt的参数一致性问题了

我现在又没法截图了
有两种情况
1. 3完之后闪退
2. 3完接2接9 报251

**Comment by xytoki** [comment]
2-3-9呢

**Comment by sylar605** [comment]
> > > > 草，我自己试了一下，得先按3再按9才能截到图，吐血
> > > 
> > > 
> > > 3不是获取坐标角度么
> > 
> > 
> > 这调试器调用函数的时候不会执行init，只按9连句柄都没拿到... 按3是强制跑一下init
> 
> 草 有无可能是nvidia experience的问题（

草不可能 这玩意我就没装过

**Comment by HuanLinOTO** [comment]
> 2-3-9呢

251

**Comment by xytoki** [comment]
![Snipaste_2022-12-29_20-39-12](https://user-images.githubusercontent.com/7547189/209952309-5d61f6ca-66df-47f1-a365-eaa885882c76.png)

OBS测试：开启“窗口化游戏优化”后，OBS也只能抓到一帧

**Comment by HuanLinOTO** [comment]
> ![Snipaste_2022-12-29_20-39-12](https://user-images.githubusercontent.com/7547189/209952309-5d61f6ca-66df-47f1-a365-eaa885882c76.png)
> 
> OBS测试：开启“窗口化游戏优化”后，OBS也只能抓到一帧

坏了 我也出现只能抓到一帧的情况了

**Comment by sylar605** [comment]
草还真是 那破案了

**Comment by HuanLinOTO** [comment]
> 草还真是 那破案了

等等 我21h2也出现这个情况 压根就没这个设置选项=-=

**Comment by xytoki** [comment]
HKEY_CURRENT_USER\Software\Microsoft\DirectX\GraphicsSettings
![Snipaste_2022-12-29_20-44-29](https://user-images.githubusercontent.com/7547189/209952836-f0e197d3-aef4-4383-b992-b44b74cb2087.png)
HKEY_CURRENT_USER\Software\Microsoft\DirectX\UserGpuPreferences
![Snipaste_2022-12-29_20-45-08](https://user-images.githubusercontent.com/7547189/209952917-766ce1a3-c53b-4f96-b37e-9556f3315bf3.png)

这是那个设置对应的注册表

**Comment by Bilx-ZL** [comment]
我去，破案了，默默看你们讨论了半天，去关了**窗口化游戏优化**，地图能正常追踪了！！！！
————————————————
**能追踪但是处于不可用状态，到处乱飘。**

**Comment by xytoki** [comment]
OBS在win10推荐用WGC来抓屏的...我总不能写一套WGC API吧...
先去查查（

**Comment by HuanLinOTO** [comment]
先别close 我还没...

**Comment by xytoki** [comment]
不会close（）

**Comment by xytoki** [comment]
这问题得找个 能100%解决的方案

**Comment by xytoki** [comment]
我去查一下WGC有没有透明通道，如果有的话大不了写一套基于wgc的抓屏接口

**Comment by HuanLinOTO** [comment]
![image](https://user-images.githubusercontent.com/94176676/209953219-2ed6a381-7df8-4444-a9d4-70a855654a2c.png)
无此项。。。

**Comment by xytoki** [comment]
看看系统版本是多少

**Comment by HuanLinOTO** [comment]
> 

21h2

**Comment by xytoki** [comment]
21H2应该就不是这个问题了，不过既然OBS也抓不到，肯定和bitblt兼容性有关系

**Comment by HuanLinOTO** [comment]
> 21H2应该就不是这个问题了，不过既然OBS也抓不到，肯定和bitblt兼容性有关系

我obs抓得到全部 但是调试器只能抓到一帧

**Comment by HuanLinOTO** [comment]
> 21H2应该就不是这个问题了，不过既然OBS也抓不到，肯定和bitblt兼容性有关系

问点智障问题 22h2咋更新（）
![image](https://user-images.githubusercontent.com/94176676/209953849-a792ad61-7e05-4e50-91ba-e50969c22ac4.png)

**Comment by xytoki** [comment]
> > 21H2应该就不是这个问题了，不过既然OBS也抓不到，肯定和bitblt兼容性有关系
> 
> 我obs抓得到全部 但是调试器只能抓到一帧

OBS能抓到全部的话，调试器2-3-9-3-9（每次9之前按一次3）试试看呢？

**Comment by HuanLinOTO** [comment]
> 

唔。。试了好几次了 基本上能成功截图的概率很低。。。

**Comment by HuanLinOTO** [comment]
> > > 21H2应该就不是这个问题了，不过既然OBS也抓不到，肯定和bitblt兼容性有关系
> > 
> > 
> > 我obs抓得到全部 但是调试器只能抓到一帧
> 
> OBS能抓到全部的话，调试器2-3-9-3-9（每次9之前按一次3）试试看呢？

不行

**Comment by xytoki** [comment]
> 我去，破案了，默默看你们讨论了半天，去关了**窗口化游戏优化**，地图能正常追踪了！！！！ ———————————————— **能追踪但是处于不可用状态，到处乱飘。**

到处乱飘的话，你目前是在游戏里的哪个区域？分辨率、抗锯齿分别是什么呢？

**Comment by Bilx-ZL** [comment]
> > 我去，破案了，默默看你们讨论了半天，去关了**窗口化游戏优化**，地图能正常追踪了！！！！ ———————————————— **能追踪但是处于不可用状态，到处乱飘。**
> 
> 到处乱飘的话，你目前是在游戏里的哪个区域？分辨率、抗锯齿分别是什么呢？

我在 风起地 和 龙脊雪山 测试的，还有稻妻的其它位置都一样。表现为，角色不动没事，地图能正确识别镜头朝向，角色开始移动时，定位立即乱飘，全地图瞬移，包括全黑（地图边界外），静止下来后大概5秒能恢复。且不能按M打开地图，按M开地图会立即提示 “地图识别失败：Bitblt模式下未能检测到派蒙” 。

显示器分辨率3840x2160 原神窗口分辨率2560x1440 抗锯齿SMAA

**Comment by sylar605** [comment]
> 我去，破案了，默默看你们讨论了半天，去关了**窗口化游戏优化**，地图能正常追踪了！！！！ ———————————————— **能追踪但是处于不可用状态，到处乱飘。**

我去 还真可以了 我的倒是没怎么乱飘 2K分辨率 无边框窗口化

**Comment by xytoki** [comment]
> > > 我去，破案了，默默看你们讨论了半天，去关了**窗口化游戏优化**，地图能正常追踪了！！！！ ———————————————— **能追踪但是处于不可用状态，到处乱飘。**
> > 
> > 
> > 到处乱飘的话，你目前是在游戏里的哪个区域？分辨率、抗锯齿分别是什么呢？
> 
> 我在 风起地 和 龙脊雪山 测试的，还有稻妻的其它位置都一样。表现为，角色不动没事，地图能正确识别镜头朝向，角色开始移动时，定位立即乱飘，全地图瞬移，包括全黑（地图边界外），静止下来后大概5秒能恢复。且不能按M打开地图，按M开地图会立即提示 “地图识别失败：Bitblt模式下未能检测到派蒙” 。
> 
> 显示器分辨率3840x2160 原神窗口分辨率2560x1440 抗锯齿SMAA

打开地图这个我去处理一下，乱飘暂时不太确定原因，明天跟一下cvautotrack今晚的新版之后再调调看，然后下版本会增加对窗口化游戏优化的检测和提示

**Comment by HuanLinOTO** [comment]
我能够成功追踪了， 但是在
![image](https://user-images.githubusercontent.com/94176676/210036389-1d6eeb89-afc7-4d6a-8558-e6d8a3b92c75.png)
测试的时候出现了在蒙德与该地方乱飘的情况

**Comment by Bilx-ZL** [comment]
> > > > 我去，破案了，默默看你们讨论了半天，去关了**窗口化游戏优化**，地图能正常追踪了！！！！ ———————————————— **能追踪但是处于不可用状态，到处乱飘。**
> > > 
> > > 
> > > 到处乱飘的话，你目前是在游戏里的哪个区域？分辨率、抗锯齿分别是什么呢？
> > 
> > 
> > 我在 风起地 和 龙脊雪山 测试的，还有稻妻的其它位置都一样。表现为，角色不动没事，地图能正确识别镜头朝向，角色开始移动时，定位立即乱飘，全地图瞬移，包括全黑（地图边界外），静止下来后大概5秒能恢复。且不能按M打开地图，按M开地图会立即提示 “地图识别失败：Bitblt模式下未能检测到派蒙” 。
> > 显示器分辨率3840x2160 原神窗口分辨率2560x1440 抗锯齿SMAA
> 
> 打开地图这个我去处理一下，乱飘暂时不太确定原因，明天跟一下cvautotrack今晚的新版之后再调调看，然后下版本会增加对窗口化游戏优化的检测和提示

今天仔细试了下，乱飘在地图没太多信息时，比如风起地一大片纯色块时，或者一片水的时候会，其他时候可以当作正常的。按m依然会提示，但关掉地图马上就恢复了。 我觉得关了窗口化游戏优化后，主要问题好像一下子就解决了。

**Comment by char-46** [comment]
> 我目前是22H2 Release Preview，自己机子是能正常的；dll编译有action，可以fork了然后用action跑一下。 只调试DLL、不开霜华和志琼的方法： 下载[`TEST_cvAutoTrack_Cpp.exe`](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/releases/download/7.3.3/TEST_cvAutoTrack_Cpp.exe) ([来源：GengGode/GenshinImpact_AutoTrack_DLL/releases/tag/7.3.3](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL/releases/tag/7.3.3))，和DLL放一起，管理员身份运行，就能直接调dll的接口，方便确认问题

这个 repo 被 ban 了，后人想调试也不知道怎么下手了。

**Comment by xytoki** [comment]
> 这个 repo 被 ban 了，后人想调试也不知道怎么下手了。

https://github.com/genggode/cvAutoTrack

**Comment by Bilx-ZL** [comment]
功能已被修复。

**Comment by HuanLinOTO** [comment]
2024/2/6 再次触发这个问题
![image](https://github.com/YuehaiTeam/zhiqiong/assets/94176676/92e91d2c-00bc-4e78-9c9c-79a10b4601d7)

obs 正常捕获

![image](https://github.com/YuehaiTeam/zhiqiong/assets/94176676/598ca518-be4a-470b-aa07-899eb3fc61c5)

调试 DLL 工具 3-2-9 （bitblt+截图，其中 3 报错）后获取到图片，此后再次截图获取到的都是同一帧

![image](https://github.com/YuehaiTeam/zhiqiong/assets/94176676/b57beb28-c92e-4a36-be14-5adc5584335c)

调试 DLL 工具 3-4 报错 1001 ，5 报错 2001，6 报错 3001

原神分辨率 2560x1089

已关闭窗口化游戏优化
