### ISSUE TITLE
未检测到原神窗口

### ISSUE THREAD

**Issue by ChishFoxcat** [YuehaiTeam/zhiqiong#2]
## Issue img
![uyCaw.gif](https://s1.328888.xyz/2022/08/07/uyCaw.gif)
![uyGNJ.png](https://s1.328888.xyz/2022/08/07/uyGNJ.png)
## Issue description
使用提瓦特大地图和至琼原神地图油猴插件，cocogoat插件允许后，提示未检测到原神窗口

**Comment by xytoki** [comment]
找不到窗口的问题得去 [cvautotrack](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL) 发issue或者他们的群(538198823)问问，追踪用的是他们的内核

**Comment by ChishFoxcat** [comment]
> 找不到窗口的问题得去 [cvautotrack](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL) 发issue或者他们的群(538198823)问问，追踪用的是他们的内核

收到

**Comment by LaoshuBaby** [comment]
![图片](https://user-images.githubusercontent.com/42690037/197382327-8c2d0ae4-07e8-4dbf-8f2b-cd6dc4038e5f.png)
可能遇到了相同的问题？
@ChishFoxcat 的图片看不到了，所以不知道是不是一样的情况
![图片](https://user-images.githubusercontent.com/42690037/197382376-b22725e0-f779-428b-96be-5bf2362c41cb.png)
椰羊插件是提示连接成功的

**Comment by xytoki** [comment]
未找到窗口都得去[cvautotrack](https://github.com/GengGode/GenshinImpact_AutoTrack_DLL)那边催，我这确实暂时解决不了
