### ISSUE TITLE
无法连接到   zhiqiong.vercel.app

### ISSUE THREAD

**Issue by QAQQL** [YuehaiTeam/zhiqiong#3]
![图片](https://user-images.githubusercontent.com/51136763/187018059-2168017c-f63c-43be-8c9e-6ba5efced938.png)

![图片](https://user-images.githubusercontent.com/51136763/187018196-438f64c8-748a-4a5f-9022-c9a6128fc256.png)

**Comment by xytoki** [comment]
Vercel在国内受到DNS污染。
hosts zhiqiong.vercel.app到76.76.21.98可以暂时解决，现在正在发不依赖vercel的版本。

**Comment by QAQQL** [comment]
替换host,刷新DNS后问题未能解决,请更新后推送一下分支

**Comment by xytoki** [comment]
https://github.com/YuehaiTeam/zhiqiong/commit/b89a5416d623a4101f724a33956097da72a6b515
挺早就更新了，理论上关掉这个消息框就能看到检查更新的提示，或者直接到 https://zhiqiong.cocogoat.work 下新的安装包
