### ISSUE TITLE
目前还没有支持跟踪须弥地图吗？

### ISSUE THREAD

**Issue by d13187** [YuehaiTeam/zhiqiong#4]

**Comment by xytoki** [comment]
没有，要催可以去 https://github.com/GengGode/GenshinImpact_AutoTrack_DLL 催（

**Comment by RAMBOO1990** [comment]
天理已经更新dll6.1.51支持须弥了，快更新吧~

**Comment by RAMBOO1990** [comment]
DLL已经额更新6.1.51支持须弥了，快更新吧~

**Comment by xytoki** [comment]
他那边还有bug，更新了不能用

**Comment by xytoki** [comment]
一直在群里跟进，等能用了自然会推

**Comment by xytoki** [comment]
cvautotrack更新了稳定可用的版本，已推送，现在应该可以追踪须弥
