### ISSUE TITLE
支援國際服 (hoyolab)

### ISSUE THREAD

**Issue by seriaati** [YuehaiTeam/zhiqiong#5]
目前登入似乎只能用米遊社

**Comment by seriaati** [comment]
我覺得這個想法很棒，但是這個位置辨識的準確度…

**Comment by xytoki** [comment]
左下角按钮右键切换地图选择hoyolab就是国际服了，定位准确度问题可以到https://github.com/GengGode/GenshinImpact_AutoTrack_DLL 提
