### ISSUE TITLE
使用游戏手柄UI时坐标不匹配

### ISSUE THREAD

**Issue by CODE-LA-LI-LU-LE-LO** [YuehaiTeam/zhiqiong#8]
![image](https://user-images.githubusercontent.com/8914838/193407333-bd197064-82e6-4362-8c4e-a771e1afbff3.png)
![image](https://user-images.githubusercontent.com/8914838/193407339-9cf101c8-1d53-4d1c-8d40-e6b261575aeb.png)
顶部：游戏内
底部：Hoyolab 地图
地图上的位置显示在实际位置的左侧
使用鼠标和键盘UI时正常显示

**Comment by xytoki** [comment]
Curretly joystick is not supported by the `GenshinImpact_AutoTrack_DLL` project, so just use mouse and keyboard instead.

--------

`GenshinImpact_AutoTrack_DLL` 目前不支持手柄，还请暂时使用键盘和鼠标。

**Comment by CODE-LA-LI-LU-LE-LO** [comment]
😫
